Odev/Areas/Admin/Controllers/SliderController.cs
using Odev.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Odev.Models;

namespace Odev.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SliderController : Controller
    {
        RSLNREntities db = new RSLNREntities();
        // GET: Admin/Slider
        public ActionResult Index()
        {
            var model = db.Slider.OrderByDescending(x => x.SliderID).ToList();
            return View(model);       
        }

        public ActionResult Ekle()
        {
            return View();
        }

        public ActionResult SlideraEkle(SliderModel model)
        {
            string dosyaadi = String.Empty;
            if (model.Resim != null && model.Resim.ContentLength > 0)
            {
                dosyaadi = model.Resim.FileName;
                var yol = Path.Combine(Server.MapPath("/Content/images/slide/"), dosyaadi);
                model.Resim.SaveAs(yol);



                Slider slider = new Slider();
                slider.BaslangicTarihi = model.BaslangicTarihi;
                slider.BitisTarihi = model.BitisTarihi;
                slider.ResimYolu = "/Content/images/slide/" + dosyaadi;

                db.Slider.Add(slider);
                db.SaveChanges();
            }


            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Duzenle(int id)
        {
            var model = db.Slider.Find(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Duzenle(Slider model)
        {
            if(ModelState.IsValid)
            {
                db.Slider.Attach(model);
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Sil(int id)
        {
            var model = db.Slider.Find(id);
            return View(model);
        }

        [HttpGet]
        public ActionResult SilOnay(int id)
        {
            var model = db.Slider.Find(id);
            db.Slider.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        


    }

}

Odev/Areas/Admin/Views/Slider/Duzenle.cshtml
@model Odev.Slider

@{
    ViewBag.Title = "Duzenle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SliderID)

        <div class="form-group">
            @Html.LabelFor(model => model.BaslangicTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BaslangicTarihi, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.BaslangicTarihi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BitisTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BitisTarihi, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.BitisTarihi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResimYolu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResimYolu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResimYolu, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Geri Dön", "Index")
</div>

@section pluginscss
{
    <link rel="stylesheet" type="text/css" href="~/assets/plugins/form-datepicker/css/datepicker3.css" />
    <link rel='stylesheet' type='text/css' href='~/assets/plugins/jqueryui-timepicker/jquery.ui.timepicker.css' />
    <link rel='stylesheet' type='text/css' href='~/assets/plugins/form-datepicker/css/datepicker.css' />
}

@section jsplugins
{
    <script type='text/javascript' src='~/assets/plugins/codeprettifier/prettify.js'></script>
    <script type='text/javascript' src='~/assets/plugins/easypiechart/jquery.easypiechart.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/sparklines/jquery.sparklines.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/form-toggle/toggle.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/jqueryui-timepicker/jquery.ui.timepicker.min.js'></script>
    <script type="text/javascript" src="~/assets/plugins/form-datepicker/js/locales/bootstrap-datepicker.tr.js"></script>
}
@section scripts
{
    <script type="text/javascript">
        $('.datepicker').datepicker({
            format: 'dd.mm.yyyy'
        });

    </script>
}

Odev/Areas/Admin/Views/Slider/Ekle.cshtml
@model Odev.Areas.Admin.Models.SliderModel

@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<div id="page-heading">
    <ol class="breadcrumb">
        <li class="atv">Admin</li>
        <li class="atn">Slider</li>
        <li class="active">Slider Ekle</li>
    </ol>
    <h1>Yeni Slider Ekleme</h1>
    <div class="options">
        <div class="btn-toolbar">
            <div class="btn-group hidden-xs">
               
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4>Slider Ekle</h4>
                </div>
                @using (Html.BeginForm("SlideraEkle", "Slider", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
                {
                    <div class="panel-body">
                      
                        <br>
                        <div class="form-group">
                           
                            <div class="col-sm-6">
                                
                            </div>
                            <div class="col-sm-3">
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Başlangıç Tarihi", new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.BaslangicTarihi, new { @class = "form-control datepicker", placeholder = "Başlangıç Tarihi" })
                            </div>
                            <div class="col-sm-3">
                                <p class="help-block">Slider ' ın gösterime başlayacağı tarihi giriniz</p>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Bitiş Tarihi", new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.BitisTarihi, new { @class = "form-control datepicker", placeholder = "Bitiş Tarihi" })
                            </div>
                            <div class="col-sm-3">
                                <p class="help-block">Slider ' ın gösterimden kaldırılacağı tarihi giriniz</p>
                            </div>
                        </div>
                        <div class="form-group">
                           
                            @Html.Label("Slider Resmi", new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.Resim, new { @class = "form-control", placeholder = "Resim Yolu", type = "file" })
                            </div>
                            <div class="col-sm-3">
                                <p class="help-block">Slider ' ı seçiniz.</p>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-sm-6 col-sm-offset-3">
                                <div class="btn-toolbar">
                                    <button class="btn-primary btn">Ekle</button>
                                    <a href="/Admin/Home/Index"><button class="btn-default btn">Vazgeç</button></a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section pluginscss
{
    <link rel="stylesheet" type="text/css" href="~/assets/plugins/form-datepicker/css/datepicker3.css" />
    <link rel='stylesheet' type='text/css' href='~/assets/plugins/jqueryui-timepicker/jquery.ui.timepicker.css' />
    <link rel='stylesheet' type='text/css' href='~/assets/plugins/form-datepicker/css/datepicker.css' />
}

@section jsplugins
{
    <script type='text/javascript' src='~/assets/plugins/codeprettifier/prettify.js'></script>
    <script type='text/javascript' src='~/assets/plugins/easypiechart/jquery.easypiechart.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/sparklines/jquery.sparklines.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/form-toggle/toggle.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/jqueryui-timepicker/jquery.ui.timepicker.min.js'></script>
    <script type="text/javascript" src="~/assets/plugins/form-datepicker/js/locales/bootstrap-datepicker.tr.js"></script>
}
@section scripts
{
    <script type="text/javascript">
        $('.datepicker').datepicker({
            format: 'dd.mm.yyyy'
        });

    </script>
}

Odev/Areas/Admin/Views/Slider/Index.cshtml
@model List<Slider>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

    <link rel='stylesheet' type='text/css' href='~/assets/plugins/datatables/dataTables.css' />
    <link rel="stylesheet" type="text/css" href="~/assets/plugins/codeprettifier/prettify.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/plugins/form-toggle/toggles.css" />


<div id="page-heading">
    <ol class="breadcrumb">
        <li class="atv">Admin</li>
        <li class="atn">Slider</li>
        <li class="active">Slider Listesi</li>
    </ol>

    <h1>Slider Listesi</h1>
    <div class="options">
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-sky">
                <div class="panel-heading">
                    <h4>Slider Listesi</h4>
                    <div class="options">
                        <a href="javascript:;"><i class="fa fa-cog"></i></a>
                        <a href="javascript:;"><i class="fa fa-wrench"></i></a>
                        <a href="javascript:;" class="panel-collapse"><i class="fa fa-chevron-down"></i></a>
                    </div>
                </div>
                <div class="panel-body collapse in">
                    <table cellpadding="0" cellspacing="0" border="1" class="table table-striped table-bordered datatables">
                        <thead>
                            <tr>
                                <th class="col-md-1">#ID</th>
                                <th>Başlangıç Tarihi</th>
                                <th>Bitiş Tarihi</th>
                                <th>Resim</th>
                                <th>İşlem</th>
                            </tr>
                        </thead>
                       <tbody>


                           @foreach (var item in Model)
                           {
                               <tr>
                                   <td>@item.SliderID</td>
                                   <td>@item.BaslangicTarihi</td>
                                   <td>@item.BitisTarihi</td>
                                   <td><img src="@item.ResimYolu" style="max-width:400px;max-height:100px;" /></td>
                                   <td>@Html.ActionLink("Düzenle", "Duzenle", "Slider", new { id = item.SliderID }, null) | @Html.ActionLink("Sil", "Sil", "Slider", new { id = item.SliderID }, null) </td>
                               </tr>
                           }
                       </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div> <!-- container -->



<script type="text/javascript" src="~/Scripts/jquery-2.1.4.js"></script>
<script type="text/javascript" src="~/assets/js/jqueryui-1.10.3.min.js"></script>
<script type="text/javascript" src="~/assets/js/bootstrap.min.js"></script>
<script type="text/javascript" src="~/assets/js/enquire.js"></script>
<script type="text/javascript" src="~/assets/js/jquery.cookie.js"></script>
<script type="text/javascript" src="~/assets/js/jquery.nicescroll.min.js"></script>
<script type="text/javascript" src="~/assets/plugins/codeprettifier/prettify.js"></script>
<script type="text/javascript" src="~/assets/plugins/easypiechart/jquery.easypiechart.min.js"></script>
<script type="text/javascript" src="~/assets/plugins/sparklines/jquery.sparklines.min.js"></script>
<script type="text/javascript" src="~/assets/plugins/form-toggle/toggle.min.js"></script>
<script type="text/javascript" src="~/assets/plugins/datatables/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="~/assets/plugins/datatables/dataTables.bootstrap.js"></script>
<script type="text/javascript" src="~/assets/js/placeholdr.js"></script>
<script type="text/javascript" src="~/assets/js/application.js"></script>
<script type="text/javascript" src="~/assets/demo/demo.js"></script>

Odev/Areas/Admin/Views/Slider/Sil.cshtml
@model Odev.Slider

@{
    ViewBag.Title = "Sil";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Sil</h2>

<h3>Silmek istediğinize emin misiniz?</h3>
<div>
    <h4>Slider</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BaslangicTarihi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BaslangicTarihi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BitisTarihi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BitisTarihi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResimYolu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResimYolu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Resim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Resim)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="fc-button">
            @Html.ActionLink("Sil", "SilOnay", new { id = Model.SliderID} , new { @class = "btn btn-danger" })
        </div>
    }
</div>