Odev/Areas/Admin/Controllers/UrunController.cs
using Odev.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Odev.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UrunController : Controller
    {
        RSLNREntities db = new RSLNREntities();
        // GET: Admin/Urun
        public ActionResult Index()
        {
            var model = db.Urunler.OrderByDescending(x => x.UrunID).ToList();
            return View(model);
        }


        public ActionResult Ekle()
        {
            return View();
        }

        public ActionResult UruneEkle(AdminUrun model)
        {
            string dosyaadi = String.Empty;
            if (model.Resim != null && model.Resim.ContentLength > 0)
            {
                dosyaadi = model.Resim.FileName;
                var yol = Path.Combine(Server.MapPath("/Content/images/Urunler/"), dosyaadi);
                model.Resim.SaveAs(yol);


                Urunler urun = new Urunler();
                urun.KategoriID = model.Kategori.KategoriID;
                urun.MarkaID = model.Markalar.MarkaID;
                urun.UrunModel = model.UrunModel;
                urun.UrunOzellikler = model.UrunOzellikler;
                urun.UrunFiyat = model.UrunFiyat;
                urun.UrunFotoYol = "/Content/images/Urunler/" + dosyaadi;


                db.Urunler.Add(urun);
                db.SaveChanges();
            }


            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult Duzenle(int id)
        {

            var model = db.Urunler.Find(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Duzenle(Urunler model)
        {

            if (ModelState.IsValid)
            {
                var bulunan = db.Urunler.Find(model.UrunID);
                bulunan.KategoriID = model.KategoriID;
                bulunan.MarkaID = model.MarkaID;
                bulunan.UrunFiyat = model.UrunFiyat;
                bulunan.UrunFotoYol = model.UrunFotoYol;
                bulunan.UrunModel = model.UrunModel;
                bulunan.UrunOzellikler = model.UrunOzellikler;
                
                db.SaveChanges();

            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Sil(int id)
        {
            var model = db.Urunler.Find(id);
            return View(model);
        }

        [HttpGet]
        public ActionResult SilOnay(int id)
        {
            var model = db.Urunler.Find(id);
            db.Urunler.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }



}

Odev/Areas/Admin/Views/Urun/Duzenle.cshtml
@model Odev.Urunler

@{
    ViewBag.Title = "Duzenle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(x => x.UrunID);
        <div class="form-group">
            @Html.Label("Kategori Adı", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.KategoriID, Odev.Areas.Admin.Models.AdminUrun.DropdownHelper.KategorilerCek(), new { @class = "btn btn-default dropdown-toggle"})
                @Html.ValidationMessageFor(model => model.Kategori.KategoriAdi, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.Label("Markalar", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MarkaID, Odev.Areas.Admin.Models.AdminUrun.DropdownHelper.MarkalariCek(), new { @class = "btn btn-default dropdown-toggle" })
                @Html.ValidationMessageFor(model => model.Markalar.MarkaAd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UrunModel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UrunModel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrunModel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UrunOzellikler, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UrunOzellikler, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrunOzellikler, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UrunFiyat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UrunFiyat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrunFiyat, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.UrunFotoYol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UrunFotoYol, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrunFotoYol, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Geri Dön", "Index")
</div>

Odev/Areas/Admin/Views/Urun/Ekle.cshtml
@model Odev.Areas.Admin.Models.AdminUrun

@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<div id="page-heading">
    <ol class="breadcrumb">
        <li class="atv">Admin</li>
        <li class="atn">Ürün</li>
        <li class="active">Ürün Ekle</li>
    </ol>
    <h1>Yeni Ürün Ekleme</h1>
    <div class="options">
        <div class="btn-toolbar">
            <div class="btn-group hidden-xs">

            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h4>Ürün Ekle</h4>
                    </div>
                    @using (Html.BeginForm("UruneEkle", "Urun", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
                    {
                        <br />
                        <div class="form-group">
                            @Html.Label("Kategori Adı", new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.DropDownListFor(model => model.Kategori.KategoriID, Odev.Areas.Admin.Models.AdminUrun.DropdownHelper.KategorilerCek(), new { @class = "btn btn-default dropdown-toggle" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Marka", new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.DropDownListFor(model => model.Markalar.MarkaID, Odev.Areas.Admin.Models.AdminUrun.DropdownHelper.MarkalariCek(), new { @class = "btn btn-default dropdown-toggle" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Model", new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.UrunModel, new { @class = "form-control"})
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Özellikler", new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextAreaFor(m => m.UrunOzellikler, new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Fiyat", new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.UrunFiyat, new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group">

                            @Html.Label("Ürün Resmi", new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.Resim, new { @class = "form-control", type = "file" })
                            </div>
                            
                        </div>

                        <div class="panel-footer">
                            <div class="row">
                                <div class="col-sm-6 col-sm-offset-3">
                                    <div class="btn-toolbar">
                                        <button class="btn-primary btn">Ekle</button>
                                        <a href="/Admin/Home/Index"><button class="btn-default btn">Vazgeç</button></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>

    @section pluginscss
{
        <link rel="stylesheet" type="text/css" href="~/assets/plugins/form-datepicker/css/datepicker3.css" />
        <link rel='stylesheet' type='text/css' href='~/assets/plugins/jqueryui-timepicker/jquery.ui.timepicker.css' />
        <link rel='stylesheet' type='text/css' href='~/assets/plugins/form-datepicker/css/datepicker.css' />
    }

    @section jsplugins
{
        <script type='text/javascript' src='~/assets/plugins/codeprettifier/prettify.js'></script>
        <script type='text/javascript' src='~/assets/plugins/easypiechart/jquery.easypiechart.min.js'></script>
        <script type='text/javascript' src='~/assets/plugins/sparklines/jquery.sparklines.min.js'></script>
        <script type='text/javascript' src='~/assets/plugins/form-toggle/toggle.min.js'></script>
        <script type='text/javascript' src='~/assets/plugins/jqueryui-timepicker/jquery.ui.timepicker.min.js'></script>
        <script type="text/javascript" src="~/assets/plugins/form-datepicker/js/locales/bootstrap-datepicker.tr.js"></script>
    }
    @section scripts
{
        <script type="text/javascript">
            $('.datepicker').datepicker({
                format: 'dd.mm.yyyy'
            });

        </script>
    }

Odev/Areas/Admin/Views/Urun/Index.cshtml
@model List<Urunler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<link rel='stylesheet' type='text/css' href='~/assets/plugins/datatables/dataTables.css' />
<link rel="stylesheet" type="text/css" href="~/assets/plugins/codeprettifier/prettify.css" />
<link rel="stylesheet" type="text/css" href="~/assets/plugins/form-toggle/toggles.css" />


<div id="page-heading">
    
        <ol class="breadcrumb">
            <li class="atv">Admin</li>
            <li class="atn">Slider</li>
            <li class="active">Slider Listesi</li>
        </ol>
    

    <h1>Ürünler Listesi</h1>
    <div class="options">
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-sky">
                <div class="panel-heading">
                    <h4>Ürünler Listesi</h4>
                    <div class="options">
                        <a href="javascript:;"><i class="fa fa-cog"></i></a>
                        <a href="javascript:;"><i class="fa fa-wrench"></i></a>
                        <a href="javascript:;" class="panel-collapse"><i class="fa fa-chevron-down"></i></a>
                    </div>
                </div>
                <div class="panel-body collapse in">
                    <table cellpadding="0" cellspacing="0" border="1" class="table table-striped table-bordered datatables" id="details">
                        <thead>
                            <tr>
                                <th class="col-md-1">#ID</th>
                                <th class="col-md-3">Ürün Fotoğrafı</th>
                                <th>Kategori</th>
                                <th>Marka</th>
                                <th>Model</th>
                                <th>Özellikler</th>
                                <th>Fiyat</th>
                                <th>İşlem</th>
                            </tr>
                        </thead>
                        <tbody>


                            @foreach (var item in Model)
                            {
                                Baglanti a = new Baglanti();
                                a.Baglantilar(item);
                                <tr>
                                    <td>@item.UrunID</td>
                                    <td><img src="@item.UrunFotoYol"  class="col-md-10" /></td>
                                    <td>@item.Kategori.KategoriAdi</td>
                                    <td>@item.Markalar.MarkaAd</td>
                                    <td>@item.UrunModel</td>
                                    <td>@item.UrunOzellikler</td>
                                    <td>@item.UrunFiyat</td>
                                    <td>@Html.ActionLink("Düzenle", "Duzenle", "Urun", new { id = item.UrunID }, null) | @Html.ActionLink("Sil", "Sil", "Urun", new { id = item.UrunID }, null) </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div> <!-- container -->



<script type="text/javascript" src="~/Scripts/jquery-2.1.4.js"></script>
<script type="text/javascript" src="~/assets/js/jqueryui-1.10.3.min.js"></script>
<script type="text/javascript" src="~/assets/js/bootstrap.min.js"></script>
<script type="text/javascript" src="~/assets/js/enquire.js"></script>
<script type="text/javascript" src="~/assets/js/jquery.cookie.js"></script>
<script type="text/javascript" src="~/assets/js/jquery.nicescroll.min.js"></script>
<script type="text/javascript" src="~/assets/plugins/codeprettifier/prettify.js"></script>
<script type="text/javascript" src="~/assets/plugins/easypiechart/jquery.easypiechart.min.js"></script>
<script type="text/javascript" src="~/assets/plugins/sparklines/jquery.sparklines.min.js"></script>
<script type="text/javascript" src="~/assets/plugins/form-toggle/toggle.min.js"></script>
<script type="text/javascript" src="~/assets/plugins/datatables/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="~/assets/plugins/datatables/dataTables.bootstrap.js"></script>
<script type="text/javascript" src="~/assets/js/placeholdr.js"></script>
<script type="text/javascript" src="~/assets/js/application.js"></script>
<script type="text/javascript" src="~/assets/demo/demo.js"></script>

Odev/Areas/Admin/Views/Urun/Sil.cshtml
@model Odev.Urunler

@{
    ViewBag.Title = "Sil";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Sil</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Urunler</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UrunFotoYol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UrunFotoYol)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UrunModel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UrunModel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UrunOzellikler)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UrunOzellikler)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UrunFiyat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UrunFiyat)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="accordion-toggle fc-button">
            <a href="/Admin/Urun"><button class="btn btn-danger">Vazgeç</button></a>
            @Html.ActionLink("Sil", "SilOnay", new { id = Model.UrunID }, new { @class = "btn btn-danger" })
        </div>
    }
</div>