Odev/Controllers/BilgisayarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Odev.Models;

namespace Odev.Controllers
{
    public class BilgisayarController : Controller
    {
        RSLNREntities db = new RSLNREntities();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Notebooklar()
        {
            var liste = db.Urunler.Where(x => x.KategoriID == 1).ToList();
            return View(liste);
        }

        public ActionResult OyunBilgisayarlari()
        {
            var liste = db.Urunler.Where(x => x.KategoriID == 2).ToList();
            return View(liste);
        }

        public ActionResult Ikisi1AradaBilgisayarlar()
        {
            var liste = db.Urunler.Where(x => x.KategoriID == 3).ToList();
            return View(liste);
        }

        public ActionResult AllInOneBilgisayarlar()
        {
            var liste = db.Urunler.Where(x => x.KategoriID == 4).ToList();
            return View(liste);
        }

    }
}

Odev/Controllers/SepetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Odev.Models;
using Microsoft.AspNet.Identity;


namespace Odev.Controllers
{
    public class SepetController : Controller
    {
        RSLNREntities db = new RSLNREntities();
        
        // GET: Sepet
        public ActionResult Index()
        {
            string user = User.Identity.GetUserId();
            var model = db.Sepet.Where(x => x.SepetSahibi == user).ToList();
            return View(model);
        }

        public ActionResult SepeteEkle(int id)
        {
            var bulunan = db.Urunler.Find(id);
            Sepet sepet = new Sepet();
            sepet.SepetSahibi = User.Identity.GetUserId();
            sepet.UrunID = bulunan.UrunID;
            db.Sepet.Add(sepet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult SepettenCikar(int id)
        {
            var model = db.Sepet.Find(id);
            return View(model);
        }

        [HttpGet]
        public ActionResult SepettenCikarOnay(int id)
        {
            var model = db.Sepet.Find(id);
            db.Sepet.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Odev/Views/Bilgisayar/AllInOneBilgisayarlar.cshtml
@model IEnumerable<Urunler>
@{
    ViewBag.Title = "All in One Bilgisayarlar";
}

<link rel='stylesheet' type='text/css' href='~/assets/plugins/datatables/dataTables.css' />
<link rel="stylesheet" type="text/css" href="~/assets/plugins/codeprettifier/prettify.css" />
<link rel="stylesheet" type="text/css" href="~/assets/plugins/form-toggle/toggles.css" />

<div class="container">
    <div class="page-title clearfix">
        <div class="row">
            <div class="col-md-12">
                <h6><a href="..">Ana Sayfa</a></h6>
                <h6><a href="/Bilgisayar">Bilgisayarlar</a></h6>
                <h6><span class="page-active">All in One Bilgisayarlar</span></h6>
            </div>
        </div>
    </div>
</div>
<br /><div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h4>All in One Bilgisayarlar Listesi</h4>
                    <div class="options">
                    </div>
                </div>
                <div class="panel-body collapse in">
                    <table cellpadding="0" cellspacing="0" border="1" class="table table-striped table-bordered datatables" id="demo-type-table">
                        <thead>
                            <tr>
                                <th class="col-md-4"><b>ÜRÜN FOTOĞRAFI</b></th>
                                <th class="col-md-2"><b>ÜRÜN MARKASI</b></th>
                                <th class="col-md-2"><b>ÜRÜN MODELİ</b></th>
                                <th class="col-md-3"><b>ÜRÜN ÖZELLİKLERİ</b></th>
                                <th class="col-md-4"><b>ÜRÜNÜN FİYATI</b></th>
                                <th class="col-md-5"><b>İŞLEM SEÇENEKLERİ</b></th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td><img class="col-md-12" src="@item.UrunFotoYol" /></td>
                                    <td>@item.Markalar.MarkaAd</td>
                                    <td>@item.UrunModel</td>
                                    <td>@item.UrunOzellikler</td>
                                    <td>@item.UrunFiyat ₺</td>
                                    <td>
                                       @{
                                           if (User.Identity.IsAuthenticated == true)
                                           { @Html.ActionLink("Sepete Ekle", "SepeteEkle", "Sepet", new { id = item.UrunID }, null)}
                                           else
                                           {
                                            <br /><br />
                                                <a href="/Account/Register" class="btn btn-block btn-danger">Kayıt Ol</a>
                                                <br />
                                                <a href="/Account/Login" class="btn btn-block btn-danger">Giriş Yap</a>
                                                <br />
                                           }

                                    }
                                    </td>
                                </tr>
                             }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

@Styles.Render("~/Content/css")

@Scripts.Render("~/bundles/modernizr")
@Scripts.Render("~/Script/jquery")
<link rel='stylesheet' type='text/css' href='~/assets/plugins/form-daterangepicker/daterangepicker-bs3.css' />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/form-markdown/css/bootstrap-markdown.min.css' />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/codeprettifier/prettify.css' />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/form-toggle/toggles.css' />
<link rel="stylesheet" type="text/css" href="~/assets/plugins/form-datepicker/css/datepicker3.css" />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/jqueryui-timepicker/jquery.ui.timepicker.css' />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/form-datepicker/css/datepicker.css' />


@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")

<script type='text/javascript' src='~/assets/plugins/datatables/jquery.dataTables.min.js'></script>
<script type='text/javascript' src='~/assets/plugins/datatables/dataTables.bootstrap.js'></script>
<script type='text/javascript' src='~/assets/demo/demo-datatables.js'></script>

Odev/Views/Bilgisayar/Ikisi1AradaBilgisayarlar.cshtml
@model IEnumerable<Urunler>
@{
    ViewBag.Title = "2si 1 Arada Bilgisayarlar";
}

<link rel='stylesheet' type='text/css' href='~/assets/plugins/datatables/dataTables.css' />
<link rel="stylesheet" type="text/css" href="~/assets/plugins/codeprettifier/prettify.css" />
<link rel="stylesheet" type="text/css" href="~/assets/plugins/form-toggle/toggles.css" />

<div class="container">
    <div class="page-title clearfix">
        <div class="row">
            <div class="col-md-12">
                <h6><a href="..">Ana Sayfa</a></h6>
                <h6><a href="/Bilgisayar">Bilgisayarlar</a></h6>
                <h6><span class="page-active">2'si 1 Arada Bilgisayarlar</span></h6>
            </div>
        </div>
    </div>
</div>
<br /><div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h4>2'si 1 Arada Bilgisayarlar Listesi</h4>
                    <div class="options">
                    </div>
                </div>
                <div class="panel-body collapse in">
                    <table cellpadding="0" cellspacing="0" border="1" class="table table-striped table-bordered datatables" id="demo-type-table">
                        <thead>
                            <tr>
                                <th class="col-md-4"><b>ÜRÜN FOTOĞRAFI</b></th>
                                <th class="col-md-2"><b>ÜRÜN MARKASI</b></th>
                                <th class="col-md-2"><b>ÜRÜN MODELİ</b></th>
                                <th class="col-md-3"><b>ÜRÜN ÖZELLİKLERİ</b></th>
                                <th class="col-md-4"><b>ÜRÜNÜN FİYATI</b></th>
                                <th class="col-md-5"><b>İŞLEM SEÇENEKLERİ</b></th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td><img class="col-md-12" src="@item.UrunFotoYol" /></td>
                                    <td>@item.Markalar.MarkaAd</td>
                                    <td>@item.UrunModel</td>
                                    <td>@item.UrunOzellikler</td>
                                    <td>@item.UrunFiyat ₺</td>
                                    <td>
                                        @{
                                            if (User.Identity.IsAuthenticated == true)
                                            { @Html.ActionLink("Sepete Ekle", "SepeteEkle", "Sepet", new { id = item.UrunID }, null)}
                                            else
                                            {
                                                <br /><br />
                                                <a href="/Account/Register" class="btn btn-block btn-danger">Kayıt Ol</a>
                                                <br />
                                                <a href="/Account/Login" class="btn btn-block btn-danger">Giriş Yap</a>
                                                <br />
                                            }

                                        }
                                    </td>
                                </tr>
                                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

@Styles.Render("~/Content/css")

@Scripts.Render("~/bundles/modernizr")
@Scripts.Render("~/Script/jquery")
<link rel='stylesheet' type='text/css' href='~/assets/plugins/form-daterangepicker/daterangepicker-bs3.css' />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/form-markdown/css/bootstrap-markdown.min.css' />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/codeprettifier/prettify.css' />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/form-toggle/toggles.css' />
<link rel="stylesheet" type="text/css" href="~/assets/plugins/form-datepicker/css/datepicker3.css" />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/jqueryui-timepicker/jquery.ui.timepicker.css' />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/form-datepicker/css/datepicker.css' />

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")

<script type='text/javascript' src='~/assets/plugins/datatables/jquery.dataTables.min.js'></script>
<script type='text/javascript' src='~/assets/plugins/datatables/dataTables.bootstrap.js'></script>
<script type='text/javascript' src='~/assets/demo/demo-datatables.js'></script>

Odev/Views/Bilgisayar/Index.cshtml
@{
    ViewBag.Title = "Bilgisayarlar";
}

<div class="container">
    <div class="page-title clearfix">
        <div class="row">
            <div class="col-md-12">
                <h6><a href="..">Ana Sayfa</a></h6>
                <h6><span class="page-active">Bilgisayarlar</span></h6>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">

        <div class="col-md-6">
            <div class="widget-main">
                <div class="widget-main-title">
                    <h4 class="widget-title">NOTEBOOK BİLGİSAYARLAR</h4>
                </div>
                <div class="widget-inner">
                    <a href="~/Bilgisayar/Notebooklar"><img src="~/Content/images/NotebookShowroom.jpg" /></a>
                </div>
            </div>
        </div>


        <div class="col-md-6">
            <div class="widget-main">
                <div class="widget-main-title">
                    <h4 class="widget-title">OYUN BİLGİSAYARLARI</h4>
                </div>
                <div class="widget-inner">
                    <a href="~/Bilgisayar/OyunBilgisayarlari"><img src="~/Content/images/OyunBilgisayarıShowroom.jpg" /></a>
                </div>
            </div>
        </div>


        <div class="col-md-6">
            <div class="widget-main">
                <div class="widget-main-title">
                    <h4 class="widget-title">2 Sİ 1 ARADA BİLGİSAYARLAR</h4>
                </div>
                <div class="widget-inner">
                    <a href="~/Bilgisayar/Ikisi1AradaBilgisayarlar"><img src="~/Content/images/2si1AradaShowroom.jpg" /></a>
                </div>
            </div>
        </div>


        <div class="col-md-6">
            <div class="widget-main">
                <div class="widget-main-title">
                    <h4 class="widget-title">ALL IN ONE BİLGİSAYARLAR</h4>
                </div>
                <div class="widget-inner">
                    <a href="~/Bilgisayar/AllInOneBilgisayarlar"><img src="~/Content/images/AllinOneShowroom.jpg" /></a>
                </div>
            </div>
        </div>

    </div>
</div>

Odev/Views/Bilgisayar/Notebooklar.cshtml
@model List<Urunler>
@{
    ViewBag.Title = "Notebooklar";
}

<link rel='stylesheet' type='text/css' href='~/assets/plugins/datatables/dataTables.css' />
<link rel="stylesheet" type="text/css" href="~/assets/plugins/codeprettifier/prettify.css" />
<link rel="stylesheet" type="text/css" href="~/assets/plugins/form-toggle/toggles.css" />

<div class="container">
    <div class="page-title clearfix">
        <div class="row">
            <div class="col-md-12">
                <h6><a href="..">Ana Sayfa</a></h6>
                <h6><a href="/Bilgisayar">Bilgisayarlar</a></h6>
                <h6><span class="page-active">Notebooklar</span></h6>
            </div>
        </div>
    </div>
</div>
<br />
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h4>Notebook Listesi</h4>
                    <div class="options">
                    </div>
                </div>
                <div class="panel-body collapse in">
                    <table cellpadding="0" cellspacing="0" border="1" class="table table-striped table-bordered datatables" id="demo-type-table">
                        <thead>
                            <tr>
                                <th class="col-md-4"><b>ÜRÜN FOTOĞRAFI</b></th>
                                <th class="col-md-2"><b>ÜRÜN MARKASI</b></th>
                                <th class="col-md-2"><b>ÜRÜN MODELİ</b></th>
                                <th class="col-md-3"><b>ÜRÜN ÖZELLİKLERİ</b></th>
                                <th class="col-md-4"><b>ÜRÜNÜN FİYATI</b></th>
                                <th class="col-md-5"><b>İŞLEM SEÇENEKLERİ</b></th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td><img class="col-md-12" src="@item.UrunFotoYol" /></td>
                                    <td>@item.Markalar.MarkaAd</td>
                                    <td>@item.UrunModel</td>
                                    <td>@item.UrunOzellikler</td>
                                    <td>@item.UrunFiyat ₺</td>
                                    <td>
                                        @{
                                            if (User.Identity.IsAuthenticated == true)
                                            { @Html.ActionLink("Sepete Ekle", "SepeteEkle", "Sepet", new { id = item.UrunID }, null)}
                                            else
                                            {
                                                <br /><br />
                                                <a href="/Account/Register" class="btn btn-block btn-danger">Kayıt Ol</a>
                                                <br />
                                                <a href="/Account/Login" class="btn btn-block btn-danger">Giriş Yap</a>
                                                <br />
                                            }

                                        }
                                    </td>
                                </tr>
                             }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

@Styles.Render("~/Content/css")

@Scripts.Render("~/bundles/modernizr")
@Scripts.Render("~/Script/jquery")
<link rel='stylesheet' type='text/css' href='~/assets/plugins/form-daterangepicker/daterangepicker-bs3.css' />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/form-markdown/css/bootstrap-markdown.min.css' />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/codeprettifier/prettify.css' />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/form-toggle/toggles.css' />
<link rel="stylesheet" type="text/css" href="~/assets/plugins/form-datepicker/css/datepicker3.css" />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/jqueryui-timepicker/jquery.ui.timepicker.css' />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/form-datepicker/css/datepicker.css' />

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")

<script type='text/javascript' src='~/assets/plugins/datatables/jquery.dataTables.min.js'></script>
<script type='text/javascript' src='~/assets/plugins/datatables/dataTables.bootstrap.js'></script>
<script type='text/javascript' src='~/assets/demo/demo-datatables.js'></script>

Odev/Views/Bilgisayar/OyunBilgisayarlari.cshtml
@model IEnumerable<Urunler>
@{
    ViewBag.Title = "Oyun Bilgisayarlar";
}

<link rel='stylesheet' type='text/css' href='~/assets/plugins/datatables/dataTables.css' />
<link rel="stylesheet" type="text/css" href="~/assets/plugins/codeprettifier/prettify.css" />
<link rel="stylesheet" type="text/css" href="~/assets/plugins/form-toggle/toggles.css" />

<div class="container">
    <div class="page-title clearfix">
        <div class="row">
            <div class="col-md-12">
                <h6><a href="..">Ana Sayfa</a></h6>
                <h6><a href="/Bilgisayar">Bilgisayarlar</a></h6>
                <h6><span class="page-active">Oyun Bilgisayarları</span></h6>
            </div>
        </div>
    </div>
</div>
<br />
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h4>Oyun Bilgisayarları Listesi</h4>
                    <div class="options">
                    </div>
                </div>
                <div class="panel-body collapse in">
                    <table cellpadding="0" cellspacing="0" border="1" class="table table-striped table-bordered datatables" id="demo-type-table">
                        <thead>
                            <tr>
                                <th class="col-md-4"><b>ÜRÜN FOTOĞRAFI</b></th>
                                <th class="col-md-2"><b>ÜRÜN MARKASI</b></th>
                                <th class="col-md-2"><b>ÜRÜN MODELİ</b></th>
                                <th class="col-md-3"><b>ÜRÜN ÖZELLİKLERİ</b></th>
                                <th class="col-md-4"><b>ÜRÜNÜN FİYATI</b></th>
                                <th class="col-md-5"><b>İŞLEM SEÇENEKLERİ</b></th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td><img class="col-md-12" src="@item.UrunFotoYol" /></td>
                                    <td>@item.Markalar.MarkaAd</td>
                                    <td>@item.UrunModel</td>
                                    <td>@item.UrunOzellikler</td>
                                    <td>@item.UrunFiyat ₺</td>
                                    <td>
                                        @{
                                            if (User.Identity.IsAuthenticated == true)
                                            { @Html.ActionLink("Sepete Ekle", "SepeteEkle", "Sepet", new { id = item.UrunID }, null)}
                                            else
                                            {
                                                <br /><br />
                                                <a href="/Account/Register" class="btn btn-block btn-danger">Kayıt Ol</a>
                                                <br />
                                                <a href="/Account/Login" class="btn btn-block btn-danger">Giriş Yap</a>
                                                <br />
                                            }

                                        }
                                    </td>
                                </tr>
                                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

@Styles.Render("~/Content/css")

@Scripts.Render("~/bundles/modernizr")
@Scripts.Render("~/Script/jquery")
<link rel='stylesheet' type='text/css' href='~/assets/plugins/form-daterangepicker/daterangepicker-bs3.css' />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/form-markdown/css/bootstrap-markdown.min.css' />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/codeprettifier/prettify.css' />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/form-toggle/toggles.css' />
<link rel="stylesheet" type="text/css" href="~/assets/plugins/form-datepicker/css/datepicker3.css" />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/jqueryui-timepicker/jquery.ui.timepicker.css' />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/form-datepicker/css/datepicker.css' />

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")

<script type='text/javascript' src='~/assets/plugins/datatables/jquery.dataTables.min.js'></script>
<script type='text/javascript' src='~/assets/plugins/datatables/dataTables.bootstrap.js'></script>
<script type='text/javascript' src='~/assets/demo/demo-datatables.js'></script>