Odev/Controllers/BilgisayarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Odev.Models;

namespace Odev.Controllers
{
    public class BilgisayarController : Controller
    {
        RSLNREntities db = new RSLNREntities();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Notebooklar()
        {
            var liste = db.Urunler.Where(x => x.KategoriID == 1).ToList();
            return View(liste);
        }

        public ActionResult OyunBilgisayarlari()
        {
            var liste = db.Urunler.Where(x => x.KategoriID == 2).ToList();
            return View(liste);
        }

        public ActionResult Ikisi1AradaBilgisayarlar()
        {
            var liste = db.Urunler.Where(x => x.KategoriID == 3).ToList();
            return View(liste);
        }

        public ActionResult AllInOneBilgisayarlar()
        {
            var liste = db.Urunler.Where(x => x.KategoriID == 4).ToList();
            return View(liste);
        }

    }
}

Odev/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Odev.Models;

namespace Odev.Controllers
{
    public class AnaSayfaController : Controller
    {
        RSLNREntities db = new RSLNREntities();
        
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult _Slider()
        {
            var liste = db.Slider.Where(x=>x.BaslangicTarihi<DateTime.Now && x.BitisTarihi >DateTime.Now).OrderByDescending(x => x.SliderID);
            return View(liste);
        }

        public ActionResult _BilgisayarSlider()
        {
            var liste = db.Urunler.Where(x=>x.KategoriID <=4).OrderByDescending(x=>x.UrunID);
            return View(liste);
        }

        public ActionResult _TelefonSlider()
        {
            var liste = db.Urunler.Where(x => x.KategoriID == 5).OrderByDescending(x => x.UrunID);
            return View(liste);
        }

        public ActionResult _SesMuzikSlider()
        {
            var liste = db.Urunler.Where(x => x.KategoriID == 6).OrderByDescending(x => x.UrunID);
            return View(liste);
        }

    }
}

Odev/Controllers/OyunKonsollariController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Odev.Models;

namespace Odev.Controllers
{
    public class OyunKonsollariController : Controller
    {
        RSLNREntities db = new RSLNREntities();
        // GET: OyunKonsollari
        public ActionResult Index()
        {
            var liste = db.Urunler.Where(x => x.KategoriID == 8);
            return View(liste);
        }
        
    }
}

Odev/Controllers/SesMuzikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Odev.Models;

namespace Odev.Controllers
{
    public class SesMuzikController : Controller
    {
        RSLNREntities db = new RSLNREntities();
        // GET: SesMuzik
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SesSistemleri()
        {
            var liste = db.Urunler.Where(x => x.KategoriID == 6);
            return View(liste);
        }

        public ActionResult DigerSesAygitlari()
        {
            var liste = db.Urunler.Where(x => x.KategoriID == 7);
            return View(liste);
        }

       
    }
}

Odev/Views/Shared/_GirisYapilmisLayout.cshtml
<!DOCTYPE html>
<html class="no-js" lang="tr">
<head>
    <title>RSLNR - ONLINE AVM</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="RSLNR">
    <meta name="author" content="RSLNR">
    <meta charset="UTF-8">

    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800' rel='stylesheet' type='text/css'>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Script/jquery")
    

</head>
<body>
    <div class="responsive-navigation visible-sm visible-xs">
        <a href="#" class="menu-toggle-btn">
            <i class="fa fa-bars"></i>
        </a>
        <div class="responsive_menu">
            <ul class="main_menu">
                <li>@Html.ActionLink("Ana Sayfa", "Index", "Home")</li>
                <li>
                    @Html.ActionLink("Bilgisayarlar", "Index", "Bilgisayar")
                    <ul>
                        <li>@Html.ActionLink("Notebook Bilgisayarlar", "Notebooklar", "Bilgisayar")</li>
                        <li>@Html.ActionLink("Oyun Bilgisayarları", "OyunBilgisayarlari", "Bilgisayar")</li>
                        <li>@Html.ActionLink("2'Si 1 Arada Bilgisayarlar", "Ikisi1AradaBilgisayarlar", "Bilgisayar")</li>
                        <li>@Html.ActionLink("All in One Bilgisayarlar", "AllInOneBilgisayarlar", "Bilgisayar")</li>
                    </ul>
                </li>
                <li>@Html.ActionLink("Telefonlar", "Index", "Telefonlar")</li>
                <li>
                    @Html.ActionLink("Ses ve Müzik", "Index", "SesMuzik")
                    <ul>
                        <li>
                            @Html.ActionLink("Ses Sistemleri", "SesSistemleri", "SesMuzik")
                        </li>
                        <li>
                            @Html.ActionLink("Diğer Ses Aygıtları", "DigerSesAygitlari", "SesMuzik")
                        </li>
                    </ul>
                </li>
                <li>@Html.ActionLink("Oyun Konsolları", "Index", "OyunKonsollari")</li>
                <li>@Html.ActionLink("Bilgisayar Aksesuarları", "Index", "BilgisayarAksesuarlari")</li>
                <li>@Html.ActionLink("Telefon Aksesuarları", "Index", "TelefonAksesuarlari")</li>
                <li>@Html.ActionLink("Sepet","Index","Sepet")</li>
            </ul>

        </div>
    </div>
    <header class="site-header">
        <div class="container">
            <div class="row">
                <div class="col-md-4 header-left">
                </div>
                <div class="col-md-4">
                    <div class="logo">
                        <a href="Index" title="RSLNR" rel="home">
                            <h3 style="color:#e9e9e9;">RSLNR</h3>
                            <h3 style="color:#c6badd; margin-top:0px;">ONLINE AVM</h3>
                        </a>
                    </div>
                </div>
                <div class="col-md-4 header-right">
                    <ul class="small-links">
                        @Html.Partial("_LoginPartial")
                    </ul>
                </div>
            </div>
        </div>
        <div class="nav-bar-main" role="navigation">
            <div class="container">
                <nav class="main-navigation clearfix visible-md visible-lg" role="navigation">
                    <ul class="main-menu sf-menu">
                        <li>@Html.ActionLink("Ana Sayfa", "Index", "Home")</li>
                        <li>
                            @Html.ActionLink("Bilgisayarlar", "Index", "Bilgisayar")
                            <ul>
                                <li>@Html.ActionLink("Notebook Bilgisayarlar", "Notebooklar", "Bilgisayar")</li>
                                <li>@Html.ActionLink("Oyun Bilgisayarları", "OyunBilgisayarlari", "Bilgisayar")</li>
                                <li>@Html.ActionLink("2'Si 1 Arada Bilgisayarlar", "Ikisi1AradaBilgisayarlar", "Bilgisayar")</li>
                                <li>@Html.ActionLink("All in One Bilgisayarlar", "AllInOneBilgisayarlar", "Bilgisayar")</li>
                            </ul>
                        </li>
                        <li>@Html.ActionLink("Telefonlar", "Index", "Telefonlar")</li>
                        <li>
                            @Html.ActionLink("Ses ve Müzik", "Index", "SesMuzik")
                            <ul>
                                <li>
                                    @Html.ActionLink("Ses Sistemleri", "SesSistemleri", "SesMuzik")
                                </li>
                                <li>
                                    @Html.ActionLink("Diğer Ses Aygıtları", "DigerSesAygitlari", "SesMuzik")
                                </li>
                            </ul>
                        </li>
                        <li>@Html.ActionLink("Oyun Konsolları", "Index", "OyunKonsollari")</li>
                        <li>@Html.ActionLink("Bilgisayar Aksesuarları", "Index", "BilgisayarAksesuarlari")</li>
                        <li>@Html.ActionLink("Telefon Aksesuarları", "Index", "TelefonAksesuarlari")</li>
                        <li><a href="/Sepet"><span>SEPET   <i class="fa fa-shopping-cart"></i></span></a></li>
                    </ul>

                </nav>
            </div>
        </div>
    </header>
    <div class="container">
        @RenderBody()
    </div>
    <footer class="site-footer">
        <div class="container">
            <div class="bottom-footer">
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-4">
                        <ul class="footer-nav">
                            <li>@Html.ActionLink("Ana Sayfa", "Index", "Home")</li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                    </div>
                </div>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Scripts", false)
</body>
</html>

Odev/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="no-js" lang="tr">
<head>
    <title>RSLNR - ONLINE AVM</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="RSLNR">
    <meta name="author" content="RSLNR">
    <meta charset="UTF-8">

    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800' rel='stylesheet' type='text/css'>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Script/jquery")

</head>
<body>
    <div class="responsive-navigation visible-sm visible-xs">
        <a href="#" class="menu-toggle-btn">
            <i class="fa fa-bars"></i>
        </a>
        <div class="responsive_menu">
            <ul class="main_menu">
                <li>@Html.ActionLink("Ana Sayfa", "Index", "AnaSayfa")</li>
                <li>
                    @Html.ActionLink("Bilgisayarlar", "Index", "Bilgisayar")
                <ul>
                    <li>@Html.ActionLink("Notebook Bilgisayarlar", "Notebooklar", "Bilgisayar")</li>
                    <li>@Html.ActionLink("Oyun Bilgisayarları", "OyunBilgisayarlari", "Bilgisayar")</li>
                    <li>@Html.ActionLink("2'Si 1 Arada Bilgisayarlar", "Ikisi1AradaBilgisayarlar", "Bilgisayar")</li>
                    <li>@Html.ActionLink("All in One Bilgisayarlar", "AllInOneBilgisayarlar", "Bilgisayar")</li>
                </ul>
            </li>
                <li>@Html.ActionLink("Telefonlar", "Index", "Telefonlar")</li>
            <li>
                @Html.ActionLink("Ses ve Müzik", "Index", "SesMuzik")
            <ul>
                <li>
                    @Html.ActionLink("Ses Sistemleri", "SesSistemleri", "SesMuzik")</li>
                <li>
                    @Html.ActionLink("Diğer Ses Aygıtları", "DigerSesAygitlari", "SesMuzik")</li>
            </ul>
        </li>
        <li>@Html.ActionLink("Oyun Konsolları", "Index", "OyunKonsollari")</li>
        <li>@Html.ActionLink("Bilgisayar Aksesuarları", "Index", "BilgisayarAksesuarlari")</li>
        <li>@Html.ActionLink("Telefon Aksesuarları", "Index", "TelefonAksesuarlari")</li>
    </ul>

</div>
</div>
<header class="site-header">
    <div class="container">
        <div class="row">
            <div class="col-md-4 header-left">
            </div>
            <div class="col-md-4">
                <div class="logo">
                    <a href="Index" title="RSLNR" rel="AnaSayfa">
                        <h3 style="color:#e9e9e9;">RSLNR</h3>
                        <h3 style="color:#c6badd; margin-top:0px;">ONLINE AVM</h3>
                    </a>
                </div>
            </div>
            <div class="col-md-4 header-right">
                <ul class="small-links">
                    @Html.Partial("_LoginPartial")
                </ul>
                <div class="search-form">
                    <form name="search_form" method="get" action="#" class="search_form">
                        <input type="text" name="s" placeholder="Sitede arama..." title="Sitede arama..." class="field_search">
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="nav-bar-main" role="navigation">
        <div class="container">
            <nav class="main-navigation clearfix visible-md visible-lg" role="navigation">
                <ul class="main-menu sf-menu">
                    <li>@Html.ActionLink("Ana Sayfa", "Index", "AnaSayfa")</li>
                    <li>
                        @Html.ActionLink("Bilgisayarlar", "Index", "Bilgisayar")
                        <ul>
                            <li>@Html.ActionLink("Notebook Bilgisayarlar", "Notebooklar", "Bilgisayar")</li>
                            <li>@Html.ActionLink("Oyun Bilgisayarları", "OyunBilgisayarlari", "Bilgisayar")</li>
                            <li>@Html.ActionLink("2'Si 1 Arada Bilgisayarlar", "Ikisi1AradaBilgisayarlar", "Bilgisayar")</li>
                            <li>@Html.ActionLink("All in One Bilgisayarlar", "AllInOneBilgisayarlar", "Bilgisayar")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Telefonlar","Index","Telefonlar")</li>
                    <li>
                        @Html.ActionLink("Ses ve Müzik", "Index", "SesMuzik")
                        <ul>
                            <li>
                                @Html.ActionLink("Ses Sistemleri", "SesSistemleri", "SesMuzik")
                            </li>
                            <li>
                                @Html.ActionLink("Diğer Ses Aygıtları", "DigerSesAygitlari", "SesMuzik")
                            </li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Oyun Konsolları", "Index", "OyunKonsollari")</li>
                    <li>@Html.ActionLink("Bilgisayar Aksesuarları", "Index", "BilgisayarAksesuarlari")</li>
                    <li>@Html.ActionLink("Telefon Aksesuarları", "Index", "TelefonAksesuarlari")</li>
                </ul>

            </nav>
        </div>
    </div>
</header>
<div class="container">
    @RenderBody()
</div>
<footer class="site-footer">
    <div class="container">
        <div class="bottom-footer">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-4">
                    <ul class="footer-nav">
                        <li>@Html.ActionLink("Ana Sayfa", "Index", "AnaSayfa")</li>
                    </ul>
                </div>
                <div class="col-md-6">
                </div>
            </div>
        </div>
    </div>
</footer>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")

    @RenderSection("Scripts",false)

</body>
</html>